name: geodesy
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy>=1.24.0
  - scipy>=1.17.0
  - matplotlib>=3.0
  - pyyaml>=6.0.1
  - jupyter
  - ipython

  - pip:
    - open3d==0.19.0
    - PyQt6==6.10.2
    - scikit-learn>=1.0.0
    - pandas>=1.0.0
